development:
  adapter: sqlite3
  database: dev_database
  pool: 5
  timeout: 5000
  host: localhost

#rake to reset
test:
  adapter: postgresql
  database: test_database
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: prod_database
  pool: 5
  timeout: 5000
  host: localhost
